# Global PostgreSQL settings (for auth sharing)
global:
  postgresql:
    auth:
      username: bn_keycloak
      password: bn_keycloak
      database: bitnami_keycloak

# Keycloak Admin User Configuration
auth:
  adminUser: admin
  adminPassword: admin

# PostgreSQL Specific Configuration
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "microk8s-hostpath"
      size: 8Gi 
      accessModes:
        - ReadWriteOnce
  auth:
    username: bn_keycloak
    password: bn_keycloak
    database: bitnami_keycloak

# Additional Keycloak Environment Variables
extraEnvVars:
  - name: KC_PRODUCTION
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: VERTX_WORKER_POOL_SIZE
    value: "20"
  - name: VERTX_EVENT_LOOP_POOL_SIZE
    value: "8"
