apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
data:
  postgres-user: Ym5fa2V5Y2xvYWs=  # base64("bn_keycloak")
  postgres-password: c2VjdXJlUGFzc3dvcmQ=  # base64("securePassword123")
  database: Yml0bmFtaV9rZXljbG9haw==  # base64("bitnami_keycloak")
  username: Ym5fa2V5Y2xvYWs=  # base64("bn_keycloak")
  password: c2VjdXJlUGFzc3dvcmQ=  # base64("securePassword123")

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
type: Opaque
data:
  admin-user: YWRtaW4=  # base64("admin")
  admin-password: c2VjdXJlQWRtaW4h  # base64("secureAdminPassword!")
